package com.hongguaninfo.ocnandroid.beans;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 手机用户
 * 
 * @author Administrator
 * 
 */
public class AuthUser implements java.io.Serializable {
	/**
	 * 用户id
	 */
	private String userId;
	/**
	 * 登录名
	 */
	private String loginName;
	/**
	 * 用户密码
	 */
	private String password;
	/**
	 * 用户名
	 */
	private String userName;
	/**
	 * 用户邮箱
	 */
	private String userEmail;
	/**
	 * 站名
	 */
	private String stationName;
	/**
	 * 删除状态
	 */
	private Short delStatus;
	/**
	 * 当前状态
	 */
	private Short status;
	private BigDecimal departid;
	/**
	 * 用户工号
	 */
	private String userEmpno;
	/**
	 * 用户手机
	 */
	private String userMobile;
	/**
	 * 用户手机号
	 */
	private String userPhone;
	/**
	 * 用户性别
	 */
	private Short userSex;
	/**
	 * 用户年龄
	 */
	private Short userAge;
	/**
	 * 用户描述
	 */
	private String userDesc;
	/**
	 * 用户...
	 */
	private String userDept;
	/**
	 * 用户类型
	 */
	private String userType;
	/**
	 * 用户级别
	 */
	private String userStarLevel;
	/**
	 * 所处分公司
	 */
	private String branchCompany;
	/**
	 * 区域
	 */
	private String region;
	/**
	 * 工位
	 */
	private String station;

	/**
	 * 创建日期
	 */
	private Date createDate;
	/**
	 * 创建用户
	 */
	private Long createUser;
	/**
	 * 队列
	 */
	private String team;
	/**
	 * 地理坐标
	 */
	private String coordinate;

	public String getStationName() {
		return stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	private String userStatus;

	public String getUserStatus() {
		return userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.LOGIN_NAME
	 * 
	 * @return the value of AUTH_USER.LOGIN_NAME
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.LOGIN_NAME
	 * 
	 * @param loginName
	 *            the value for AUTH_USER.LOGIN_NAME
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName == null ? null : loginName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.PASSWORD
	 * 
	 * @return the value of AUTH_USER.PASSWORD
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.PASSWORD
	 * 
	 * @param password
	 *            the value for AUTH_USER.PASSWORD
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.USER_NAME
	 * 
	 * @return the value of AUTH_USER.USER_NAME
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.USER_NAME
	 * 
	 * @param userName
	 *            the value for AUTH_USER.USER_NAME
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.USER_EMAIL
	 * 
	 * @return the value of AUTH_USER.USER_EMAIL
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.USER_EMAIL
	 * 
	 * @param userEmail
	 *            the value for AUTH_USER.USER_EMAIL
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail == null ? null : userEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.DEPARTID
	 * 
	 * @return the value of AUTH_USER.DEPARTID
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public BigDecimal getDepartid() {
		return departid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.DEPARTID
	 * 
	 * @param departid
	 *            the value for AUTH_USER.DEPARTID
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setDepartid(BigDecimal departid) {
		this.departid = departid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.USER_EMPNO
	 * 
	 * @return the value of AUTH_USER.USER_EMPNO
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getUserEmpno() {
		return userEmpno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.USER_EMPNO
	 * 
	 * @param userEmpno
	 *            the value for AUTH_USER.USER_EMPNO
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setUserEmpno(String userEmpno) {
		this.userEmpno = userEmpno == null ? null : userEmpno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.USER_MOBILE
	 * 
	 * @return the value of AUTH_USER.USER_MOBILE
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getUserMobile() {
		return userMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.USER_MOBILE
	 * 
	 * @param userMobile
	 *            the value for AUTH_USER.USER_MOBILE
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setUserMobile(String userMobile) {
		this.userMobile = userMobile == null ? null : userMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.USER_PHONE
	 * 
	 * @return the value of AUTH_USER.USER_PHONE
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.USER_PHONE
	 * 
	 * @param userPhone
	 *            the value for AUTH_USER.USER_PHONE
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone == null ? null : userPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.USER_SEX
	 * 
	 * @return the value of AUTH_USER.USER_SEX
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public Short getUserSex() {
		return userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.USER_SEX
	 * 
	 * @param userSex
	 *            the value for AUTH_USER.USER_SEX
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setUserSex(Short userSex) {
		this.userSex = userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.USER_AGE
	 * 
	 * @return the value of AUTH_USER.USER_AGE
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public Short getUserAge() {
		return userAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.USER_AGE
	 * 
	 * @param userAge
	 *            the value for AUTH_USER.USER_AGE
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setUserAge(Short userAge) {
		this.userAge = userAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.USER_DESC
	 * 
	 * @return the value of AUTH_USER.USER_DESC
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getUserDesc() {
		return userDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.USER_DESC
	 * 
	 * @param userDesc
	 *            the value for AUTH_USER.USER_DESC
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setUserDesc(String userDesc) {
		this.userDesc = userDesc == null ? null : userDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.USER_DEPT
	 * 
	 * @return the value of AUTH_USER.USER_DEPT
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getUserDept() {
		return userDept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.USER_DEPT
	 * 
	 * @param userDept
	 *            the value for AUTH_USER.USER_DEPT
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setUserDept(String userDept) {
		this.userDept = userDept == null ? null : userDept.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.USER_TYPE
	 * 
	 * @return the value of AUTH_USER.USER_TYPE
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.USER_TYPE
	 * 
	 * @param userType
	 *            the value for AUTH_USER.USER_TYPE
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setUserType(String userType) {
		this.userType = userType == null ? null : userType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.USER_STAR_LEVEL
	 * 
	 * @return the value of AUTH_USER.USER_STAR_LEVEL
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getUserStarLevel() {
		return userStarLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.USER_STAR_LEVEL
	 * 
	 * @param userStarLevel
	 *            the value for AUTH_USER.USER_STAR_LEVEL
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setUserStarLevel(String userStarLevel) {
		this.userStarLevel = userStarLevel == null ? null : userStarLevel
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.BRANCH_COMPANY
	 * 
	 * @return the value of AUTH_USER.BRANCH_COMPANY
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getBranchCompany() {
		return branchCompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.BRANCH_COMPANY
	 * 
	 * @param branchCompany
	 *            the value for AUTH_USER.BRANCH_COMPANY
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setBranchCompany(String branchCompany) {
		this.branchCompany = branchCompany == null ? null : branchCompany
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.REGION
	 * 
	 * @return the value of AUTH_USER.REGION
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getRegion() {
		return region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.REGION
	 * 
	 * @param region
	 *            the value for AUTH_USER.REGION
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setRegion(String region) {
		this.region = region == null ? null : region.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.STATION
	 * 
	 * @return the value of AUTH_USER.STATION
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getStation() {
		return station;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.STATION
	 * 
	 * @param station
	 *            the value for AUTH_USER.STATION
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setStation(String station) {
		this.station = station == null ? null : station.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.DEL_STATUS
	 * 
	 * @return the value of AUTH_USER.DEL_STATUS
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public Short getDelStatus() {
		return delStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.DEL_STATUS
	 * 
	 * @param delStatus
	 *            the value for AUTH_USER.DEL_STATUS
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setDelStatus(Short delStatus) {
		this.delStatus = delStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.STATUS
	 * 
	 * @return the value of AUTH_USER.STATUS
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.STATUS
	 * 
	 * @param status
	 *            the value for AUTH_USER.STATUS
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.CREATE_DATE
	 * 
	 * @return the value of AUTH_USER.CREATE_DATE
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.CREATE_DATE
	 * 
	 * @param createDate
	 *            the value for AUTH_USER.CREATE_DATE
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.CREATE_USER
	 * 
	 * @return the value of AUTH_USER.CREATE_USER
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public Long getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.CREATE_USER
	 * 
	 * @param createUser
	 *            the value for AUTH_USER.CREATE_USER
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setCreateUser(Long createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.TEAM
	 * 
	 * @return the value of AUTH_USER.TEAM
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getTeam() {
		return team;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.TEAM
	 * 
	 * @param team
	 *            the value for AUTH_USER.TEAM
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setTeam(String team) {
		this.team = team == null ? null : team.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column AUTH_USER.COORDINATE
	 * 
	 * @return the value of AUTH_USER.COORDINATE
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public String getCoordinate() {
		return coordinate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column AUTH_USER.COORDINATE
	 * 
	 * @param coordinate
	 *            the value for AUTH_USER.COORDINATE
	 * 
	 * @mbggenerated Thu Feb 02 13:46:53 CST 2012
	 */
	public void setCoordinate(String coordinate) {
		this.coordinate = coordinate == null ? null : coordinate.trim();
	}
}